/**
 * PDF export utility using PDFKit.
 * Converts a Markdown report string into a simple PDF document
 * and returns it as a Base64-encoded string.
 */
import PDFDocument from 'pdfkit';

/** Convert a Markdown report to a Base64-encoded PDF string. */
export async function markdownToPdfBase64(
  markdownReport: string,
  title: string,
): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => {
      const buf = Buffer.concat(chunks);
      resolve(buf.toString('base64'));
    });
    doc.on('error', reject);

    // Title
    doc.fontSize(18).font('Helvetica-Bold').text(title, { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown(0.5);

    // Render Markdown line-by-line with simple heuristics
    const lines = markdownReport.split('\n');
    for (const raw of lines) {
      const line = raw.trimEnd();

      if (line.startsWith('## ')) {
        doc.moveDown(0.3);
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a2e').text(line.slice(3));
        doc.fontSize(11).font('Helvetica').fillColor('#333333');
      } else if (line.startsWith('# ')) {
        doc.moveDown(0.3);
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a2e').text(line.slice(2));
        doc.fontSize(11).font('Helvetica').fillColor('#333333');
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        doc.fontSize(11).font('Helvetica').fillColor('#333333').text(`  • ${line.slice(2)}`);
      } else if (line.trim() === '') {
        doc.moveDown(0.3);
      } else {
        // Strip inline markdown (* ** `) for clean PDF text
        const clean = line
          .replace(/\*\*(.+?)\*\*/g, '$1')
          .replace(/\*(.+?)\*/g, '$1')
          .replace(/`(.+?)`/g, '$1');
        doc.fontSize(11).font('Helvetica').fillColor('#333333').text(clean);
      }
    }

    // Footer
    doc.moveDown(1);
    doc
      .fontSize(9)
      .fillColor('#888888')
      .text(
        `Generated by @sugukuru/japan-real-estate-intel-mcp — ${new Date().toLocaleDateString('ja-JP')}`,
        { align: 'center' },
      );

    doc.end();
  });
}
