/**
 * License Store — SQLite-backed persistence for issued license keys.
 *
 * Stores license keys generated by Stripe Webhook so they can be
 * looked up later by email or Stripe customer/session ID.
 */
import Database from 'better-sqlite3';
import { resolve, dirname } from 'node:path';
import { mkdirSync } from 'node:fs';
import { moduleLogger } from '../logger.js';

const log = moduleLogger('license_store');

const DB_PATH = process.env.LICENSE_DB_PATH ?? resolve(process.cwd(), 'db', 'licenses.sqlite');

let _db: Database.Database | null = null;

function getDb(): Database.Database {
  if (_db) return _db;
  mkdirSync(dirname(DB_PATH), { recursive: true });
  _db = new Database(DB_PATH);
  _db.pragma('journal_mode = WAL');
  _db.exec(`
    CREATE TABLE IF NOT EXISTS licenses (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      stripe_customer_id TEXT,
      stripe_session_id TEXT UNIQUE,
      client_name TEXT NOT NULL,
      email TEXT NOT NULL,
      tier TEXT NOT NULL CHECK(tier IN ('pro', 'enterprise')),
      license_key TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      revoked INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS idx_licenses_email ON licenses(email);
    CREATE INDEX IF NOT EXISTS idx_licenses_stripe_customer ON licenses(stripe_customer_id);
  `);
  return _db;
}

export interface StoredLicense {
  id: number;
  stripe_customer_id: string | null;
  stripe_session_id: string | null;
  client_name: string;
  email: string;
  tier: string;
  license_key: string;
  expires_at: string;
  created_at: string;
  revoked: number;
}

/**
 * Stores a newly issued license key in the database.
 */
export function issueLicense(params: {
  stripeCustomerId: string | null;
  stripeSessionId: string;
  clientName: string;
  email: string;
  tier: 'pro' | 'enterprise';
  licenseKey: string;
  expiresAt: string;
}): StoredLicense {
  const db = getDb();

  // Idempotency: if this session already has a license, return it
  const existing = db
    .prepare('SELECT * FROM licenses WHERE stripe_session_id = ?')
    .get(params.stripeSessionId) as StoredLicense | undefined;

  if (existing) {
    log.info(
      { sessionId: params.stripeSessionId },
      'License already issued for this Stripe session (idempotent)',
    );
    return existing;
  }

  const stmt = db.prepare(`
    INSERT INTO licenses (stripe_customer_id, stripe_session_id, client_name, email, tier, license_key, expires_at)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `);

  const result = stmt.run(
    params.stripeCustomerId,
    params.stripeSessionId,
    params.clientName,
    params.email,
    params.tier,
    params.licenseKey,
    params.expiresAt,
  );

  log.info(
    { id: result.lastInsertRowid, email: params.email, tier: params.tier },
    'License issued and stored',
  );

  return db.prepare('SELECT * FROM licenses WHERE id = ?').get(result.lastInsertRowid) as StoredLicense;
}

/**
 * Retrieves the license issued for a specific Stripe Checkout session.
 *
 * `stripe_session_id` is an opaque, single-use identifier that Stripe only
 * ever returns to the buyer's own browser on the checkout success redirect
 * (`?session_id={CHECKOUT_SESSION_ID}`), so — unlike an email address — it
 * cannot be guessed or enumerated by a third party.
 */
export function getLicenseBySessionId(stripeSessionId: string): StoredLicense | null {
  const db = getDb();
  const row = db
    .prepare(`SELECT * FROM licenses WHERE stripe_session_id = ? AND revoked = 0`)
    .get(stripeSessionId) as StoredLicense | undefined;
  return row ?? null;
}

/**
 * Retrieves all licenses for a Stripe customer.
 */
export function getLicensesByCustomer(stripeCustomerId: string): StoredLicense[] {
  const db = getDb();
  return db
    .prepare(
      `SELECT * FROM licenses
       WHERE stripe_customer_id = ? AND revoked = 0
       ORDER BY created_at DESC`,
    )
    .all(stripeCustomerId) as StoredLicense[];
}

/**
 * Revokes all active licenses for a Stripe customer (used on subscription cancellation).
 */
export function revokeLicensesByCustomer(stripeCustomerId: string): number {
  const db = getDb();
  const result = db
    .prepare('UPDATE licenses SET revoked = 1 WHERE stripe_customer_id = ? AND revoked = 0')
    .run(stripeCustomerId);
  log.info(
    { stripeCustomerId, revokedCount: result.changes },
    'Licenses revoked for customer',
  );
  return result.changes;
}

/** Test-only: clear all licenses */
export function clearLicensesForTests(): void {
  try {
    getDb().prepare('DELETE FROM licenses').run();
  } catch {
    // ignore
  }
}
